version: "3.7"

services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - groupchatdb

  groupchatdb:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/db_data:/var/lib/postgresql
    env_file:
      - .env
